// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CCSystem.DAL.Models;

public partial class BookingDetail
{
    public int DetailId { get; set; }

    public int BookingId { get; set; }

    public int ServiceId { get; set; }

    public DateOnly ScheduleDate { get; set; }

    public int Quantity { get; set; }

    public decimal UnitPrice { get; set; }

    public TimeOnly ScheduleTime { get; set; }

    public int? ServiceDetailId { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual ICollection<ScheduleAssignment> ScheduleAssignments { get; set; } = new List<ScheduleAssignment>();

    public virtual Service Service { get; set; }

    public virtual ServiceDetail ServiceDetail { get; set; }
}