// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CCSystem.DAL.Models;

public partial class Payment
{
    public int PaymentId { get; set; }

    public int CustomerId { get; set; }

    public int BookingId { get; set; }

    public decimal Amount { get; set; }

    public string PaymentMethod { get; set; }

    public string Status { get; set; }

    public DateTime? PaymentDate { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string Notes { get; set; }

    public string TransactionId { get; set; }

    [JsonIgnore]
    public virtual Booking Booking { get; set; }

    [JsonIgnore]
    public virtual Account Customer { get; set; }
}