// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CCSystem.DAL.Models;

public partial class ScheduleAssignment
{
    public int AssignmentId { get; set; }

    public int HousekeeperId { get; set; }

    public int DetailId { get; set; }

    public DateOnly AssignDate { get; set; }

    public TimeOnly StartTime { get; set; }

    public TimeOnly EndTime { get; set; }

    public string Status { get; set; }

    public string Notes { get; set; }

    public virtual BookingDetail Detail { get; set; }

    public virtual Account Housekeeper { get; set; }

    public virtual ICollection<Report> Reports { get; set; } = new List<Report>();
}