// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CCSystem.DAL.Models;

public partial class ServiceDetail
{
    public int ServiceDetailId { get; set; }

    public int? ServiceId { get; set; }

    public string OptionName { get; set; }

    public string OptionType { get; set; }

    public decimal? BasePrice { get; set; }

    public string Unit { get; set; }

    public int? Duration { get; set; }

    public string Description { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<BookingDetail> BookingDetails { get; set; } = new List<BookingDetail>();

    public virtual Service Service { get; set; }
}